DROP TABLE IF EXISTS ACCOUNTS;
CREATE TABLE ACCOUNTS (
  ID VARCHAR(50) PRIMARY KEY,
  ACCOUNT_NUMBER VARCHAR(50) NOT NULL,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  DOB		DATE,
  ADDRESS_1 VARCHAR(50),
  ADDRESS_2 VARCHAR(50),
  CITY      VARCHAR(50),
  REGION    VARCHAR(50),
  COUNTRY   VARCHAR(50),
  ZIP       VARCHAR(10),
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE ACCOUNTS ADD CONSTRAINT ACCOUNTS_UNQ_1 UNIQUE(ACCOUNT_NUMBER);


DROP TABLE IF EXISTS CARDS;
CREATE TABLE CARDS (
  ID VARCHAR(50) PRIMARY KEY,
  CARD_NUMBER VARCHAR(50) NOT NULL,
  EXP_MONTH VARCHAR(10) NOT NULL,
  EXP_YEAR 	VARCHAR(10) NOT NULL,
  BLOCK	    VARCHAR(1)  NOT NULL DEFAULT 'N',
  HOTLIST   VARCHAR(1) NOT NULL DEFAULT 'N',
  MAX_LIMIT  DECIMAL(10,2) NOT NULL,
  AVAILABLE_AMT  DECIMAL(10,2) NOT NULL,
  ACCOUNT_NUMBER VARCHAR(50) NOT NULL,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE CARDS ADD CONSTRAINT CARDS_UNQ_1 UNIQUE(CARD_NUMBER);


DROP TABLE IF EXISTS TRANSACTIONS;
CREATE TABLE TRANSACTIONS (
  ID VARCHAR(50) PRIMARY KEY,
  CARD_NUMBER VARCHAR(50) NOT NULL,
  TRAN_DATE_TIME DATETIME NOT NULL,
  TRAN_AMT DECIMAL(10,2) NOT NULL,
  TRAN_TYPE VARCHAR(10) NOT NULL,
  STATUS VARCHAR(10) NOT NULL,
  MERCHANT_ID VARCHAR(10) NOT NULL,
  TERMINAL_ID VARCHAR(10) NOT NULL,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
