---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service-k8s
spec:
  type: LoadBalancer
  selector:
    # This should match the app name from deployment section
    app: transaction-service
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      # nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service-deployment
  labels:
    app: transaction-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
      - name: transaction-service
        image: selvendiranj/transaction-service
        ports:
        - containerPort: 8080